// Verified against Student Book pp.4–25, Teacher Book pp.4–19,
// Grammar Book pp.4–9 and Grammar Answer Key pp.2–3.
// Open production is explicitly self-assessed, never assigned an automatic mark.
const activities = [];
const field = (label, answer, options) => ({ label, answers: Array.isArray(answer) ? answer : [answer], ...(options ? { options } : {}) });
const rows = (labels, answers, options) => labels.map((label, i) => field(label, answers[i], options));
const letters = (answers, options) => rows(answers.map((_, i) => String.fromCharCode(97 + i)), answers, options);
function add(book, page, number, title, fields = [], extra = {}) {
  const item = { id: `${book}-${page}-${number}`, book, page, number: String(number), title, fields, source: book === 'grammar' ? 'Corrigés de grammaire · Unité 1' : 'Guide pédagogique · Unité 1', ...extra };
  activities.push(item);
  return item;
}
function open(page, number, title, prompt, model, extra = {}) {
  return add('student', page, number, title, [], { type: 'open', prompt, model, ...extra });
}
const tf = ['Vrai', 'Faux'];
const pronouns = ['Je', 'Tu', 'Il', 'Elle', 'Nous', 'Vous', 'Ils', 'Elles'];
const nums = n => Array.from({ length: n }, (_, i) => String(i + 1));

add('student', 4, 1, 'Regarde les photos et identifie les langues.', rows(['La langue anglaise', 'La langue française', 'La langue arabe'], ['1','3','2'], nums(3)), { anchor: { x: 64, y: 70 }, hint: 'Choisis le numéro de la photo.' });
open(4, 2, 'Quelles langues connais-tu ?', 'Nomme les langues que tu connais.', 'Exemple : Je connais l’arabe, le français et l’anglais.', { anchor: { x: 64, y: 75 } });
add('student',5,1,'Écoute, répète et place dans l’ordre.',rows(['Bonjour, madame Rose.','Salut, Amélie.','Bonjour, Loïc.','Au revoir, Tom.'],['3','2','1','4'],nums(4)),{audio:'u1-a-1',hint:'Pour chaque image (de gauche à droite), choisis son ordre dans l’enregistrement.'});
add('student',5,2,'Je serre la main ou je fais la bise ?',rows(['À un(e) ami(e)','À ma sœur / mon frère','À un(e) inconnu(e)','À un professeur','À un(e) vendeur(euse)','À ma mère'],['Je fais la bise','Je fais la bise','Je serre la main','Je serre la main','Je serre la main','Je fais la bise'],['Je serre la main','Je fais la bise']));
add('student',6,3,'Associe chaque dialogue à une image.',rows(['a · Bonjour, les enfants !','b · Au revoir, les enfants !','c · Salut, Marie.','d · Bonjour, madame Rose.'],['3','2','4','1'],nums(4)),{audio:'u1-a-3',hint:'Choisis le numéro de la photo.'});
open(6,4,'Travaille avec un(e) ami(e).','Présente-toi et demande le nom de ton ami(e).','— Bonjour. Comment t’appelles-tu ?\n— Je m’appelle Théo. Et toi ?\n— Je m’appelle Tom.');
add('student',6,5,'Écoute et réponds.',rows(['Comment s’appelle-t-il ?','Comment s’appelle-t-elle ?'],[['Il s’appelle Antoine','Antoine'],['Elle s’appelle Emma','Emma']]),{audio:'u1-a-5'});
open(6,6,'Présente tes camarades.','Présente un camarade et une camarade.','Exemple : Il s’appelle Tom. Elle s’appelle Emma.');
open(7,7,'Tu comprends la situation ?','Que se passe-t-il sur l’image ? Que va-t-il se passer ensuite ?','Exemple : Deux garçons font du skateboard. Un garçon fait un saut. Ils vont se saluer et se présenter.');
open(7,8,'Lis le dialogue.','Lis le dialogue d’Éric et Daniel. Compare-le à tes hypothèses.','Les garçons se disent « Salut ». Daniel apprécie le saut d’Éric. Ils se demandent leurs prénoms.');
add('student',7,9,'Trouve les trois phrases correctes.',rows(['a · Il y a cinq garçons sur la rampe.','b · Ils se disent « Salut ».','c · Un garçon tombe.','d · Son saut est horrible.','e · Il lui demande son nom.','f · Les garçons sont Éric et Daniel.'],['Faux','Vrai','Faux','Faux','Vrai','Vrai'],tf));
open(7,10,'Présente-toi et épelle ton nom.','À deux, présentez-vous et épelez vos noms et prénoms.','— Bonjour, je m’appelle Denis Muller.\n— Comment ça s’écrit ?\n— D.E.N.I.S M.U. deux L.E.R.');
add('student',8,11,'Lis et écris l’information manquante.',rows(['Bonjour à tous, je m’appelle …','Bonjour, je … Mark.','Bonjour, monsieur Antoine, … m’appelle Claire.','Et vous, … vous appelez-vous ?','Je m’appelle …'],['monsieur Antoine','m’appelle','je','comment','Marie']),{hint:'Mots : monsieur Antoine · m’appelle · je · comment · Marie'});
open(8,12,'Présente-toi ainsi que tes ami(e)s.','Écris ton prénom, épelle-le et présente un(e) ami(e).','Exemple : Je m’appelle Emma. Ça s’écrit E.M. deux M.A. Mon ami s’appelle Tom.');
open(8,13,'Qui est-ce ? Devine qui parle.','Un camarade se retourne. Un autre dit « Salut ! ». Devine qui parle.','Exemple : — Qui est-ce ? — C’est Tom.\nVérifie ta réponse avec la personne qui a parlé.');
add('student',9,1,'Écoute, répète et place dans l’ordre.',rows(['Comment ça va ?','Très bien !','Comme ci, comme ça !','Mal !','Bien !','Très mal !'],['1','2','4','5','3','6'],nums(6)),{audio:'u1-b-1',hint:'Choisis l’ordre de chaque expression dans l’enregistrement.'});
open(9,2,'Crée le même dialogue.','Avec un(e) ami(e), adapte le dialogue à vos informations.','— Salut ! Comment ça va ?\n— Ça va très bien, merci. Et toi ?\n— Ça va bien, merci.');
open(9,3,'Crée un dialogue pour l’image 2.','Écris les trois répliques des deux garçons.','— Salut Tom ! Comment ça va ?\n— Salut Robert ! Ça va très mal ! Et toi ?\n— Comme ci, comme ça !');
add('student',10,4,'Complète puis associe les dialogues aux images.',rows(['a · Comment … va ?','a · Réponse : … !','b · Salut, Amy ! … ça va ?','b · …, Lili !','b · Ça va très … !','b · Ça va bien, … !','c · …, monsieur Legrand !','c · Comment allez-… ?','c · Ça va … !','c · Dernière réponse','Image en haut à gauche · dialogue','Image en haut à droite · dialogue','Image en bas · dialogue'],['ça','Mal','Comment','Salut','bien','merci','Bonjour','vous','mal','Ça va comme ci, comme ça','c','b','a']),{audio:'u1-b-4'});
add('student',10,5,'Écoute et choisis les émotions.',rows(['Nicolas et Rose','Belle','Marie','Henri'],['Comme ci, comme ça','Très bien','Mal','Comme ci, comme ça'],['Très bien','Comme ci, comme ça','Mal']),{audio:'u1-b-5',hint:'Carol est l’exemple : très bien.'});
open(11,6,'Tu comprends la situation ?','Que se passe-t-il ? L’autre garçon va-t-il l’aider ?','Exemple : Un garçon a un problème avec son vélo. L’autre garçon va l’aider.');
open(11,7,'Lis le dialogue.','Lis le dialogue d’Henri et Antoine et vérifie tes hypothèses.','Antoine remercie Henri pour son aide. Henri répond « De rien ».');
add('student',11,8,'Vrai ou faux ?',rows(['L’image montre trois garçons.','Antoine ne se sent pas très bien.','Antoine le remercie pour son aide.','Le deuxième garçon s’appelle Éric.','Henri répond « Je t’en prie ».'],['Faux','Vrai','Vrai','Faux','Faux'],tf));
open(11,9,'Travaille avec un(e) ami(e).','Demande à ton ami(e) comment ça va et réponds à sa question.','— Comment ça va ?\n— Ça va bien. Et toi ?\n— Très bien, merci.');
open(12,10,'Écris un dialogue.','Salue la personne, présente-toi, demande comment ça va, puis dis au revoir. Petit plus : demande comment va sa famille.','— Bonjour ! Je m’appelle Emma. Et toi ?\n— Je m’appelle Tom. Comment ça va ?\n— Très bien, merci. Et ta famille ?\n— Elle va bien, merci.\n— Au revoir !\n— À bientôt !');
open(13,1,'Écoute et répète les nombres.','Écoute les nombres de un à vingt, puis répète-les à voix haute.','Un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix, onze, douze, treize, quatorze, quinze, seize, dix-sept, dix-huit, dix-neuf, vingt.',{audio:'u1-c-1'});
add('student',13,2,'Dis leur âge.',rows(['Selma','Isabelle','Théo','Luc','Karl'],[['Selma a dix-sept ans','Elle a dix-sept ans'],['Isabelle a seize ans','Elle a seize ans'],['Théo a quinze ans','Il a quinze ans'],['Luc a dix-sept ans','Il a dix-sept ans'],['Karl a quinze ans','Il a quinze ans']]),{hint:'Écris une phrase avec « avoir », comme dans l’exemple : Pierre a seize ans.'});
open(13,3,'Dis ton âge et l’âge d’un(e) ami(e).','Utilise le verbe « avoir ».','Exemple : J’ai seize ans. Mon amie a dix-sept ans.');
add('student',14,4,'Écoute et repère les erreurs.',rows(['Nom : Jean','Prénom : Durand','Âge : 18','N° étudiant : 956382164'],['Correct','Erreur','Erreur','Erreur'],['Correct','Erreur']),{audio:'u1-c-4',hint:'Repère les trois informations incorrectes de la carte, selon le corrigé.'});
add('student',14,5,'Note les informations correctes.',rows(['Nom','Prénom','Âge','N° étudiant'],['Jean','Pierre',['16','16 ans','seize','seize ans'],'957386421']),{audio:'u1-c-5'});
open(15,6,'Lis le dialogue.','Lis le dialogue entre Emma et le bibliothécaire. Observe les questions formelles.','Emma Bonnet a seize ans. Elle est à la bibliothèque. Le bibliothécaire lui demande son nom et son âge.');
add('student',15,7,'Entoure la bonne réponse.',[
 field('a · La fille est…','à la bibliothèque',['à la bibliothèque','à la maison']),field('b · Elle s’appelle…','Emma',['Marie','Emma']),field('c · Le bibliothécaire se sent…','très bien',['mal','très bien']),field('d · Emma se sent…','bien',['bien','comme ci, comme ça']),field('e · Elle a… ans.','seize',['seize','quatorze']),field('f · Voici…','votre livre',['votre livre','votre stylo']),field('g · …','Merci',['Merci','De rien'])]);
open(15,8,'Travaille avec un(e) ami(e).','Demande à ton ami(e) comment ça va et quel âge il/elle a.','— Comment ça va ?\n— Ça va bien. Et toi ?\n— Très bien. Quel âge as-tu ?\n— J’ai seize ans. Et toi ?');
open(16,9,'Remplis le questionnaire.','Réponds avec tes informations. Tu peux garder tes réponses personnelles sur cet appareil.', 'Exemples à adapter : Je m’appelle Emma. Ça va bien. J’ai seize ans. Mon amie s’appelle Sara. Elle a seize ans. Mon père s’appelle Marc. Ma sœur s’appelle Léa. Elle a douze ans.',{prompts:['Comment t’appelles-tu ?','Comment ça va ?','Quel âge as-tu ?','Comment s’appelle ton / ta meilleur(e) ami(e) ?','Quel âge a-t-il / elle ?','Comment s’appelle ton père ?','Comment s’appelle ton frère / ta sœur ?','Quel âge a ton frère / ta sœur ?','Petit plus : crée trois questions.']});
add('student',17,1,'Associe les pays aux phrases entendues.',rows(['Canada','États-Unis','Brésil','Finlande','France','Afrique du Sud','Russie','Chine','Inde','Australie'],['b','d','h','e','g','a','i','j','c','f'],'abcdefghij'.split('')),{audio:'u1-d-1',hint:'Choisis la lettre de la phrase pour chaque drapeau de la carte.'});
open(17,2,'Montre ces pays sur la carte.','Montre les dix pays de l’activité 1 sur la carte et nomme-les.','Canada, États-Unis, Brésil, Finlande, France, Afrique du Sud, Russie, Chine, Inde et Australie.');
add('student',17,3,'Complète le tableau masculin / féminin.',rows(['Suédois → féminin','Espagnol → féminin','Italienne → masculin','Belge → féminin','Coréen → féminin','Turque → masculin'],['suédoise','espagnole','italien','belge','coréenne','turc']));
add('student',18,4,'Écoute et choisis les bonnes réponses.',[field('Les personnages sont…','dans le bus',['dans la rue','dans le train','dans le bus']),field('Ils…','se présentent',['se présentent','se disent au revoir','ne parlent pas'])],{audio:'u1-d-4'});
add('student',18,5,'Associe les noms aux photos.',rows(['Photo 1','Photo 2','Photo 3','Photo 4'],[['Elle s’appelle Annabelle','Elle s’appelle Anabelle'],['Ils s’appellent Paul et Thomas','Ils s’appellent Thomas et Paul'],'Il s’appelle Boris',['Elles s’appellent Sophia et Alison','Elles s’appellent Alison et Sophia']]),{hint:'Écris une phrase avec le verbe « s’appeler ». Réécoute l’activité 4 si nécessaire.'});
add('student',18,6,'Trouve la nationalité de chaque personne.',rows(['Sophia et Alison','Annabelle','Paul et Thomas','Boris'],[['suisses','sont suisses','Sophia et Alison sont suisses'],['allemande','est allemande','Annabelle est allemande'],['anglais','sont anglais','Paul et Thomas sont anglais'],['russe','est russe','Boris est russe']]),{audio:'u1-d-6'});
add('student',18,7,'Associe les drapeaux aux photos.',rows(['Russie','Royaume-Uni','Suisse','Allemagne'],['3','2','4','1'],nums(4)));
open(19,8,'Lis les textes.','Lis les présentations de Charlotte et de Renaud.','Charlotte a dix-sept ans et elle est canadienne. Son amie Adel est allemande. Renaud a quatorze ans et il est américain. Son ami Félix est chilien.');
add('student',19,9,'Réponds aux questions.',rows(['Comment s’appelle la fille ?','Quelle est sa nationalité ?','Quel âge a-t-elle ?','Comment s’appelle son amie ?','Est-ce qu’elle est allemande ?','Comment s’appellent le garçon et son ami ?','Quelle est la nationalité du garçon ?','Quel âge a-t-il ?','Qui est chilien ?'],[
 ['Elle s’appelle Charlotte','Charlotte'],['Elle est canadienne','canadienne'],['Elle a dix-sept ans','dix-sept ans','17 ans'],['Son amie s’appelle Adel','Adel','Elle s’appelle Adel'],['Oui','Oui, elle est allemande'],['Ils s’appellent Renaud et Félix','Renaud et Félix'],['Renaud est américain','Il est américain','américain'],['Il a quatorze ans','quatorze ans','14 ans'],['Son ami Félix est chilien','Félix','Félix est chilien']]));
open(19,10,'Demande la nationalité de ton ami(e).','Travaille avec un(e) ami(e).','— Quelle est ta nationalité ?\n— Je suis jordanienne. Et toi ?\n— Je suis jordanien.');
open(20,11,'Écris un dialogue formel.','Deux personnes qui ne se connaissent pas se saluent, se présentent, demandent comment ça va, leur âge et leur nationalité, puis se disent au revoir.','— Bonjour, monsieur. Comment vous appelez-vous ?\n— Je m’appelle Paul. Et vous ?\n— Je m’appelle Marc. Comment allez-vous ?\n— Très bien, merci. Quel âge avez-vous ?\n— J’ai vingt ans. Et vous ?\n— J’ai dix-neuf ans. Quelle est votre nationalité ?\n— Je suis canadien.\n— Moi, je suis français. Au revoir !\n— À bientôt !');
add('student',22,1,'Complète avec le verbe « s’appeler ».',rows(['Il … Quentin.','Elles … Camille et Ana.','Comment t’…-tu ?','Nous … Théo et Robert.','Les garçons … Éric et Lucas.','Comment vous …-vous ?','Mon amie … Nina.','Ils … Mathis et Tom.','Mon professeur … monsieur Dupois.'],['s’appelle','s’appellent','appelles','nous appelons','s’appellent','appelez','s’appelle','s’appellent','s’appelle']));
add('student',22,2,'Classe les phrases.',rows(['Bonjour, madame Blanc.','Je m’appelle Camille.','Au revoir, monsieur Robert.','Et moi, je m’appelle Lucas.','Les amies, c’est Michelle.','Au revoir, les enfants.'],['Saluer / se présenter','Saluer / se présenter','Dire au revoir','Saluer / se présenter','Saluer / se présenter','Dire au revoir'],['Saluer / se présenter','Dire au revoir']));
add('student',22,3,'Écris l’âge avec le verbe « avoir ».',rows(['a · J’… (15)','b · Nous… (17)','c · Elle… (14)','d · Il… (16)','e · Elles… (19)'],[['ai quinze ans','J’ai quinze ans'],['avons dix-sept ans','Nous avons dix-sept ans'],['a quatorze ans','Elle a quatorze ans'],['a seize ans','Il a seize ans'],['ont dix-neuf ans','Elles ont dix-neuf ans']]));
add('student',22,4,'Écris la nationalité avec le verbe « être ».',rows(['a · Elle…','b · Nous…','c · Mes amis…','d · Je…','e · Ils…','f · Lea…','g · Il…','h · Elles…'],[['est anglaise','Elle est anglaise'],['sommes italiens','Nous sommes italiens'],['sont japonais','Mes amis sont japonais'],['suis français','suis française','Je suis français','Je suis française'],['sont argentins','Ils sont argentins'],['est canadienne','Lea est canadienne','Léa est canadienne'],['est allemand','Il est allemand'],['sont suédoises','Elles sont suédoises']]));
add('student',23,'oral','DELF · Compréhension de l’oral',[
 field('Comment s’appelle-t-il ?','Lucas',['Tom','Théo','Lucas']),field('Il dit…','Salut à tous !',['Bonjour à tous !','Salut à tous !','Merci à tous !']),field('Quelle est sa nationalité ?','Allemand',['Américain','Anglais','Allemand'])],{audio:'u1-delf-1',anchor:{x:9,y:16},points:3});
add('student',23,'reading','DELF · Compréhension des écrits',rows(['C’est une fille.','Elle s’appelle Lucie.','Ses parents l’appellent Gobbie.','Ses amis l’appellent Gobbie.','Elle est portugaise.','Elle dit « au revoir ».'],['Vrai','Faux','Faux','Vrai','Vrai','Faux'],tf),{anchor:{x:9,y:54},points:2,context:'Salut tout le monde ! Je m’appelle Gabrie, mais mes amis m’appellent Gobbie. J’ai seize ans et je suis portugaise. À bientôt.',hint:'Lis le message et indique vrai ou faux. Les questions continuent à la page 24.'});
open(24,'writing','DELF · Production écrite','Complète la fiche avec tes informations.','Exemple : Nom : Martin ; Prénom : Emma ; Âge : seize ans ; Nationalité : française.',{anchor:{x:10,y:39},prompts:['Nom','Prénom','Âge','Nationalité']});
open(24,'speaking','DELF · Production orale','Réponds à voix haute aux questions. Tu peux préparer tes réponses ici.','Exemples : Je m’appelle Emma. Ça va bien. J’ai seize ans. Je suis française. Mon professeur s’appelle monsieur Lucas. « Comment ça va ? » est informel ; « Comment allez-vous ? » est formel. Je dis « Bonjour, madame / monsieur » à une personne inconnue. Je termine par « Au revoir » ou « À bientôt ». Appeler : A.P. deux P.E.L.E.R.',{anchor:{x:10,y:64},prompts:['Comment t’appelles-tu ?','Comment ça va ?','Quel âge as-tu ?','Quelle est ta nationalité ?','Comment s’appelle ton professeur ?','Quelle est la différence entre « Comment ça va ? » et « Comment allez-vous ? » ?','Comment salues-tu une personne inconnue ?','Comment termines-tu une conversation ?','Comment s’écrit le verbe « appeler » ?']});
open(25,1,'Lis les textes pour découvrir le monde.','Lis les quatre textes sur les salutations en France.','On serre la main pour saluer. Les amis peuvent se faire la bise. On attend d’être invité avant d’utiliser le prénom d’une personne. Dans une boutique, on dit « Bonjour / Bonsoir, madame / monsieur » et « Au revoir ».');
open(25,'project','Projet · Les traditions de ton pays','Présente les traditions de ton pays. Prépare ta présentation et utilise des photos en classe.','Exemple à adapter : Dans mon pays, nous saluons les personnes avec respect. Nous utilisons des formules différentes avec les amis et avec les personnes que nous ne connaissons pas.',{anchor:{x:9,y:91}});

add('grammar',4,1,'Écris les pronoms sujets.',letters(['Elles','Il','Tu','Nous','Elle','Ils','Vous','Je'],pronouns));
add('grammar',5,2,'Associe les phrases qui ont le même sens.',rows(['Ils sont américains.','Nous avons douze ans.','Elles sont irlandaises.','Il a dix-sept ans.'],['5','2','4','1'],nums(5)),{hint:'1 · Tom a 17 ans.\n2 · Marie et moi avons douze ans.\n3 · Lucie est anglaise.\n4 · Margot et Ana sont irlandaises.\n5 · Paul et Éric sont américains.'});
add('grammar',5,3,'Réécris avec un pronom sujet.',rows(['Lucie et moi avons dix ans.','Sébastien est français.','Isabelle et Margot sont italiennes.','Jullian et toi avez dix-huit ans.','Hugo et Théo sont suisses.','Léa est anglaise.'],['Nous avons dix ans','Il est français','Elles sont italiennes','Vous avez dix-huit ans','Ils sont suisses','Elle est anglaise']));
add('grammar',5,4,'Choisis le pronom utilisé.',rows(['b · Mes amis s’appellent Pierre et Sara.','c · Ils sont allemands.','d · J’ai treize ans.','e · Pierre a douze ans.','f · Pierre, Sara et moi sommes bons amis.','g · Je suis canadienne.','h · Sara a treize ans.'],['Ils','Ils','Je','Il','Nous','Je','Elle'],pronouns),{hint:'Exemple a : Je m’appelle Marie → Je.'});
add('grammar',6,5,'Complète la terminaison de « s’appeler ».',rows(['Il s’appell… Yuan.','Elles s’appell… Julie et Camille.','Nous nous appel… Max et Jean.','Comment vous appel…-vous ?','Comment s’appell… ton ami ?','Elle s’appell… Ana.','Ils s’appell… Olivier et Luc.'],['e','ent','ons','ez','e','e','ent']));
add('grammar',6,6,'Choisis la bonne réponse.',[
 field('Comment …-tu ?','t’appelles',['s’appelle','t’appelles','vous appelez']),field('Je … Hena.','m’appelle',['s’appelle','m’appelle','nous appelons']),field('Elles … Adelle et Natalie.','s’appellent',['s’appellent','s’appelle','nous appelons']),field('Comment vous … ?','appelez-vous',['nous appelons','t’appelles','appelez-vous']),field('Nous … Nicolette et Lili.','nous appelons',['nous appelez','nous appelons','nous appelent']),field('Il … Éric.','s’appelle',['m’appelle','s’appellent','s’appelle'])]);
add('grammar',6,7,'Écris la forme de « s’appeler ».',rows(['Mon professeur … monsieur Lucas.','Mes amies … Chloé et Vivien.','Je … Henry.','Comment vous … ?','Nous … Robert et Marc.','Mes parents … monsieur et madame Garnier.'],['s’appelle','s’appellent','m’appelle','appelez-vous','nous appelons','s’appellent']));
add('grammar',7,8,'Complète avec « avoir » au présent.',rows(['Tu','Il','Elle','Nous','Vous','Ils / Elles'],['as','a','a','avons','avez','ont']));
add('grammar',7,9,'Associe les sujets aux phrases.',rows(['J’','Léa','Mon frère','Mes amis','Vous','Ma sœur et toi'],['5',['2','3'],['3','2'],'7','1','6'],nums(7)),{unique:true,hint:'1 · avez dix ans ?\n2 · a vingt ans.\n3 · a deux ans.\n4 · avons le même âge.\n5 · ai dix-huit ans.\n6 · avez quatorze ans.\n7 · ont seize ans.\nUtilise chaque numéro une seule fois. 2 et 3 sont interchangeables pour Léa et mon frère.'});
add('grammar',7,10,'Complète les phrases avec « avoir ».',rows(['J’… (12)','Nous… (8)','Mes sœurs… (15)','Pierre et Jacques… (7)','Vous… (18)','Isabelle et Anna… (9)','Il… (3)','Mon amie… (6)','Tu… (11)','Vivien et toi… (19)','Natalie et moi… (5)','Elles… (14)','J’… (13)'],[
 ['ai douze ans','J’ai douze ans'],['avons huit ans','Nous avons huit ans'],['ont quinze ans','Mes sœurs ont quinze ans'],['ont sept ans','Pierre et Jacques ont sept ans'],['avez dix-huit ans','Vous avez dix-huit ans'],['ont neuf ans','Isabelle et Anna ont neuf ans'],['a trois ans','Il a trois ans'],['a six ans','Mon amie a six ans'],['as onze ans','Tu as onze ans'],['avez dix-neuf ans','Vivien et toi avez dix-neuf ans'],['avons cinq ans','Natalie et moi avons cinq ans'],['ont quatorze ans','Elles ont quatorze ans'],['ai treize ans','J’ai treize ans']]));
add('grammar',8,11,'Complète avec le sujet du verbe « être ».',rows(['… êtes','… sont','… est','… sommes','… es','… est','… sont'],['Vous',['Ils','Elles'],['Il','Elle'],'Nous','Tu',['Il','Elle'],['Ils','Elles']],pronouns));
add('grammar',8,12,'Écris l’infinitif : « avoir » ou « être ».',rows(['Vous êtes brésiliens ?','Nous avons dix ans.','Elles sont américaines.','Elles ont onze ans.','J’ai douze ans.','Nous sommes russes.','Tu as treize ans.','Pierre a seize ans.','Pierre est anglais.','Ils sont belges.','Ils ont vingt ans.','J’ai deux ans.'],['être','avoir','être','avoir','avoir','être','avoir','avoir','être','être','avoir','avoir'],['avoir','être']));
add('grammar',8,13,'Choisis la bonne réponse.',[
 field('Elles … mexicaines.','sont',['sont','sommes','est']),field('Je … russe.','suis',['ai','suis','es']),field('Sam et toi … canadiens.','êtes',['avez','êtes','sont']),field('Tu … français.','es',['est','es','êtes']),field('Mes parents … polonais.','sont',['ont','sont','est']),field('Monsieur Blanc … anglais.','est',['es','suis','est']),field('Jean et Jaques … espagnols.','sont',['est','sont','ont']),field('Nous … sud-africains.','sommes',['sont','sommes','avons']),field('Ils … belges.','sont',['sont','sommes','est']),field('Elle … chinoise.','est',['es','suis','est']),field('Je … indienne.','suis',['sont','suis','est'])]);
add('grammar',9,14,'Complète la grille des nationalités.',rows(['🇺🇸 États-Unis (féminin)','🇦🇺 Australie (masculin)','🇮🇳 Inde (masculin)','🇨🇳 Chine (féminin)','🇫🇷 France (féminin)','🇿🇦 Afrique du Sud (féminin)','🇫🇮 Finlande (masculin)','🇸🇪 Suède (féminin)','🇮🇹 Italie (masculin)','🇧🇷 Brésil (féminin)'],['américaine','australien','indien','chinoise','française','sud-africaine','finlandais','suédoise','italien','brésilienne']),{type:'crossword',hint:'Le Canada est l’exemple : canadien. Complète les mots de la grille avec les accents.'});
add('grammar',9,15,'Classe les adjectifs du tableau.',rows(['canadien','américaine','australien','chinoise','indien','française','finlandais','sud-africaine','italien','suédoise','brésilienne'],['Masculin','Féminin','Masculin','Féminin','Masculin','Féminin','Masculin','Féminin','Masculin','Féminin','Féminin'],['Masculin','Féminin']));

export const unit1 = activities;
export const bookLabels = { student: 'Student’s Book', grammar: 'Workbook', teacher: 'Teacher’s Book', answers: 'Answer Key' };
export const sections = [
 { title: 'Ouverture', page:4 }, { title: 'A · Salut !', page:5 }, { title: 'B · Ça va ?', page:9 },
 { title: 'C · Mon âge', page:13 }, { title: 'D · Ma nationalité', page:17 },
 { title: 'Résumé', page:21 }, { title: 'Grammaire', page:22 }, { title: 'DELF', page:23 }, { title: 'Culture & projet', page:25 },
];
export const transcripts = {
 'u1-a-1': 'Bonjour, Loïc. Bonjour, Théo.\nSalut, Amélie. Salut, Emma.\nBonjour, madame Rose. Bonjour, madame Lucas. Bonjour, monsieur Henri.\nAu revoir, Tom. Au revoir, Adam.',
 'u1-a-3': 'a · Bonjour, les enfants ! Bonjour, monsieur Dubois.\nb · Au revoir, les enfants ! Au revoir, maman. À plus tard.\nc · Salut, Marie. Salut, Denice.\nd · Bonjour, madame Rose. Bonjour, madame Blanc.',
 'u1-a-5': 'Je m’appelle Antoine.\nJe m’appelle Emma.',
 'u1-b-1': 'Comment ça va ?\nTrès bien !\nBien !\nComme ci, comme ça !\nMal !\nTrès mal !',
 'u1-b-4': 'a · Salut, ma chérie ! Salut, maman ! Comment ça va ? Mal !\nb · Salut, Amy ! Comment ça va ? Salut, Lili ! Ça va très bien ! Et toi ? Ça va bien, merci !\nc · Bonjour, monsieur Legrand ! Comment allez-vous ? Bonjour, monsieur Dupuis ! Ça va mal ! Et vous ? Ça va comme ci, comme ça.',
 'u1-b-5': 'Comment ça va ? Très bien !\nComment ça va ? Comme ci, comme ça !\nComment ça va ? Très bien !\nComment ça va ? Mal !\nComment ça va ? Comme ci, comme ça !',
 'u1-c-1': 'Un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix, onze, douze, treize, quatorze, quinze, seize, dix-sept, dix-huit, dix-neuf, vingt.',
 'u1-c-4': 'Je m’appelle Jean-Pierre. J’ai seize ans. Mon numéro étudiant est le 957386421.',
 'u1-c-5': 'Nom : Jean. Prénom : Pierre. Âge : 16 ans. N° étudiant : 957386421.',
 'u1-d-1': 'a · Je suis sud-africain(e).\nb · Je suis canadien(ne).\nc · Je suis indien(ne).\nd · Je suis américain(e).\ne · Je suis finlandais(e).\nf · Je suis australien(ne).\ng · Je suis français(e).\nh · Je suis brésilien(ne).\ni · Je suis russe.\nj · Je suis chinois(e).',
 'u1-d-4': 'Les personnages sont dans le bus. Ils se présentent. Sophia et Alison sont suisses. Boris est russe. Paul et Thomas sont anglais et Annabelle est allemande.',
 'u1-d-6': 'Les personnages sont dans le bus. Ils se présentent. Sophia et Alison sont suisses. Boris est russe. Paul et Thomas sont anglais et Annabelle est allemande.',
 'u1-delf-1': 'Salut à tous. Je m’appelle Lucas. J’ai 15 ans. Je suis allemand.',
};
